bipedal-locomotion-framework: BipedalLocomotion::IK::SE3Task Class Reference
BipedalLocomotion::IK::SE3Task Class Reference
SE3Task is a concrete implementation of the Task.
#include <BipedalLocomotion/IK/SE3Task.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler) override
Initialize the task.
bool setVariableHandler (const System::VariablesHandler &variablesHandler) override
Set the set of variables required by the task.
bool update () override
Update the content of the element.
bool setSetPoint (const manif::SE3d &I_H_F, const manif::SE3d::Tangent &mixedVelocity)
Set the desired set-point of the trajectory.
std::size_t size () const override
Get the size of the task.
Type type () const override
The SE3Task is an equality task.
Public Member Functions inherited from BipedalLocomotion::IK::LinearTask
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the task.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::IK::LinearTask
enum Type { equality, inequality }
Type of the task.
Protected Member Functions inherited from BipedalLocomotion::IK::LinearTask
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::IK::LinearTask
Eigen::MatrixXd m_A
Task Matrix.
Eigen::VectorXd m_b
Task Vector.
std::string m_description {"Generic IK Task Element"}
String describing the content of the task.
std::shared_ptr< iDynTree::KinDynComputations > m_kinDyn
Pointer to a KinDynComputations object.
Detailed Description
SE3Task is a concrete implementation of the Task.
Please use this element if you want to control the position and the orientation of a given frame rigidly attached to the robot. The task assumes perfect control of the robot velocity \(\nu\) that contains the base linear and angular velocity expressed in mixed representation and the joints velocity. The task represents the following equation
\[ J \nu = \mathrm{v} ^ * \]
where \(J\) is the robot jacobian and \(\mathrm{v} ^ *\) is the desired velocity. The desired velocity is chosen such that the frame will asymptotically converge to the desired trajectory. The linear component of \(\mathrm{v} ^ *\) is computed with a standard Proportional controller in \(R^3\) while the angular velocity is computed by a Proportional controller in \(SO(3)\).
Note
Please refer to https://github.com/dic-iit/lie-group-controllers if you are interested in the implementation of the PD controllers.
The SE3Task is technically not a \(SE(3)\) space defined task, instead is a \(SO(3) \times \mathbb{R}^3\) task. Theoretically, there are differences between the two due to the different definitions of exponential maps and logarithm maps. Please consider that here the MIXED representation is used to define the 6d-velocity. You can find further details in Section 2.3.4 of https://traversaro.github.io/phd-thesis/traversaro-phd-thesis.pdf.
Definition at line 46 of file SE3Task.h.
Member Function Documentation
initialize()
bool SE3Task::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler) override virtual
Initialize the task.
Parameters
paramHandler pointer to the parameters handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_velocity_variable_name string Name of the variable contained in VariablesHandler describing the robot velocity Yes
frame_name string Name of the frame controlled by the SE3Task Yes
kp_linear double Gain of the position controller Yes
kp_angular double Gain of the orientation controller Yes
Returns
True in case of success, false otherwise. Where the generalized robot velocity is a vector containing the base spatial-velocity (expressed in mixed representation) and the joints velocity.
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::IK::LinearTask.
Definition at line 55 of file SE3Task.cpp.
References std::weak_ptr< T >::lock().
setSetPoint()
bool SE3Task::setSetPoint (const manif::SE3d & I_H_F, const manif::SE3d::Tangent & mixedVelocity)
Set the desired set-point of the trajectory.
Parameters
I_H_F Homogeneous transform between the link and the inertial frame.
mixedVelocity 6D-velocity written in mixed representation.g
Returns
True in case of success, false otherwise.
Definition at line 173 of file SE3Task.cpp.
setVariableHandler()
bool SE3Task::setVariableHandler (const System::VariablesHandler & variablesHandler) override virtual
Set the set of variables required by the task.
The variables are stored in the System::VariablesHandler.
Parameters
variablesHandler reference to a variables handler.
Note
The handler must contain a variable named as the parameter robot_velocity_variable_name stored in the parameter handler. The variable represents the generalized velocity of the robot. Where the generalized robot velocity is a vector containing the base spatial-velocity (expressed in mixed representation) and the joints velocity.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::IK::LinearTask.
Definition at line 19 of file SE3Task.cpp.
References BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), and BipedalLocomotion::System::VariablesHandler::getVariable().
size()
std::size_t SE3Task::size () const override virtual
Get the size of the task.
(I.e the number of rows of the vector b)
Returns
the size of the task.
Implements BipedalLocomotion::IK::LinearTask.
Definition at line 186 of file SE3Task.cpp.
type()
SE3Task::Type SE3Task::type () const override virtual
The SE3Task is an equality task.
Returns
the size of the task.
Implements BipedalLocomotion::IK::LinearTask.
Definition at line 191 of file SE3Task.cpp.
update()
bool SE3Task::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::IK::LinearTask.
Definition at line 147 of file SE3Task.cpp.
References BipedalLocomotion::Conversions::toEigen(), and BipedalLocomotion::Conversions::toManifRot().
The documentation for this class was generated from the following files:
IK/include/BipedalLocomotion/IK/SE3Task.h
IK/src/SE3Task.cpp